# Generated by Django 5.1.5 on 2025-02-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders_app.order",
                verbose_name="سفارش",
            ),
            preserve_default=False,
        ),
    ]
