# Generated by Django 5.1.5 on 2025-02-21 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderitems",
                to="orders_app.order",
                verbose_name="سفارش",
            ),
        ),
    ]
