# Generated by Django 5.1.5 on 2025-02-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0004_alter_orderitem_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="porudct_name",
            new_name="proudct_name",
        ),
    ]
