# Generated by Django 5.1.5 on 2025-02-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0005_rename_porudct_name_orderitem_proudct_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="proudct_name",
            new_name="product_name",
        ),
    ]
