# Generated by Django 5.1.5 on 2025-02-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0006_rename_proudct_name_orderitem_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pay_status",
            field=models.CharField(
                choices=[
                    ("not_paid", "پرداخت نشده"),
                    ("paid", "پرداخت شده"),
                    ("cancled", "لغو شده"),
                ],
                default="not_paid",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("none", "نامشخص"),
                    ("pending", "درحال انجام"),
                    ("done", "انجام شده"),
                ],
                default="none",
                max_length=100,
            ),
        ),
    ]
