# Generated by Django 5.1.5 on 2025-02-21 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0007_order_pay_status_alter_order_status"),
        ("products_app", "0018_alter_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product_name",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products_app.product",
                verbose_name="محصول",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="pay_status",
            field=models.CharField(
                choices=[
                    ("not_paid", "پرداخت نشده"),
                    ("paid", "پرداخت شده"),
                    ("cancled", "لغو شده"),
                ],
                default="not_paid",
                max_length=100,
                verbose_name="وضعیت پرداختی",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("none", "نامشخص"),
                    ("pending", "درحال انجام"),
                    ("done", "انجام شده"),
                ],
                default="none",
                max_length=100,
                verbose_name="وضعیت سفارش",
            ),
        ),
    ]
