# Generated by Django 5.1.5 on 2025-02-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0008_remove_orderitem_product_name_orderitem_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("cancled", "لغو شده"),
                    ("none", "نامشخص"),
                    ("pending", "درحال انجام"),
                    ("done", "انجام شده"),
                ],
                default="none",
                max_length=100,
                verbose_name="وضعیت سفارش",
            ),
        ),
    ]
