# Generated by Django 5.1.5 on 2025-02-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_app", "0004_customuser_reset_password_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="reset_password_token",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                unique=True,
                verbose_name="توکن بازیابی رمز عبور",
            ),
        ),
    ]
