# Generated by Django 5.1.5 on 2025-02-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_app", "0005_alter_customuser_reset_password_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="آدرس"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="شماره تلفن"
            ),
        ),
    ]
