# Generated by Django 5.1.5 on 2025-02-02 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="عنوان")),
                ("slug", models.SlugField(verbose_name="اسلاگ")),
            ],
            options={
                "verbose_name": "تگ",
                "verbose_name_plural": "تگ ها",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="عنوان")),
                ("slug", models.SlugField(verbose_name="اسلاگ")),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products_app.category",
                        verbose_name="دسته بندی مادر",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان محصول")),
                ("slug", models.SlugField(blank=True, null=True, verbose_name="اسلاگ")),
                (
                    "short_description",
                    models.CharField(max_length=165, verbose_name="توضیحات مختصر"),
                ),
                ("content", models.TextField(verbose_name="توضیحات کامل")),
                (
                    "price",
                    models.BigIntegerField(default=0, verbose_name="قیمت(تومان)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "فعال"), ("deactive", "غیرفعال")],
                        default="active",
                        max_length=50,
                        verbose_name="وضعیت محصول",
                    ),
                ),
                ("date_created", models.DateTimeField(verbose_name="تاریخ ایجاد")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products_app.category",
                        verbose_name="دسته بندی",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        to="products_app.tag", verbose_name="برچسب ها"
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان عکس")),
                (
                    "image",
                    models.ImageField(upload_to="products/images/", verbose_name="عکس"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galleries",
                        to="products_app.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "گالری",
                "verbose_name_plural": "گالری ها",
            },
        ),
    ]
