# Generated by Django 5.1.5 on 2025-02-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0004_alter_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default=1, upload_to="images/", verbose_name="عکس محصول"
            ),
            preserve_default=False,
        ),
    ]
