# Generated by Django 5.1.5 on 2025-02-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0005_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.IntegerField(default=0, verbose_name="درصد تخفیف"),
        ),
    ]
