# Generated by Django 5.1.5 on 2025-02-04 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0009_alter_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "کمترین مقدار باید صفر باشد."
                    ),
                    django.core.validators.MaxValueValidator(
                        100, "بیشتر مقدار باید 100 باشد."
                    ),
                ],
                verbose_name="درصد تخفیف",
            ),
        ),
    ]
