# Generated by Django 5.1.5 on 2025-02-04 06:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0010_alter_product_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "کمترین مقدار باید صفر باشد."
                            ),
                            django.core.validators.MaxValueValidator(
                                100, "بیشتر مقدار باید 100 باشد."
                            ),
                        ],
                        verbose_name="درصد تخفیف",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="درصد تخفیف بر روی همه محصولات موجود در دسته بندی اصافه خواهد شد.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products_app.category",
                        verbose_name="دسته بندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخفیف",
                "verbose_name_plural": "تخفیفات بر اساس دسته بندی",
            },
        ),
    ]
