# Generated by Django 5.1.5 on 2025-02-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0012_alter_product_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(verbose_name="توضیحات مختصر"),
        ),
    ]
