# Generated by Django 5.1.5 on 2025-02-06 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0013_alter_product_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان عکس")),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="توضیحات کوتاه"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products_app.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "آپشن",
                "verbose_name_plural": "آپشن ها",
            },
        ),
    ]
