# Generated by Django 5.1.5 on 2025-02-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0014_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="title",
            field=models.CharField(max_length=100, verbose_name="عنوان"),
        ),
    ]
