# Generated by Django 5.1.5 on 2025-02-11 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0015_alter_option_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="count",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "کمترین مقدار باید سفر باشد"
                    )
                ],
                verbose_name="تعداد موجود در انبار",
            ),
        ),
    ]
