# Generated by Django 5.1.5 on 2025-02-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0016_product_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="اسلاگ"
            ),
        ),
    ]
