# Generated by Django 5.1.5 on 2025-02-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0017_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="", unique=True, verbose_name="اسلاگ"),
            preserve_default=False,
        ),
    ]
