# Generated by Django 5.1.5 on 2025-02-22 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0018_alter_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=165, verbose_name="Title")),
                (
                    "keywords",
                    models.TextField(
                        help_text="مثال: چاقو، موبایل، ...", verbose_name="کلید وازه ها"
                    ),
                ),
                ("og_title", models.CharField(max_length=165, verbose_name="Og Title")),
                (
                    "description",
                    models.CharField(max_length=165, verbose_name="Description"),
                ),
                (
                    "og_description",
                    models.CharField(max_length=165, verbose_name="Og Description"),
                ),
                (
                    "og_image",
                    models.ImageField(
                        upload_to="seos/ogimages/", verbose_name="Og Image"
                    ),
                ),
                (
                    "twitter_card",
                    models.CharField(
                        choices=[
                            ("summary", "summary"),
                            ("summary_large_image", "summary_large_image"),
                            ("app", "app"),
                            ("player", "player"),
                        ],
                        default="summary_large_image",
                        max_length=100,
                        verbose_name="Twitter Card",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seos",
                        to="products_app.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سئو",
                "verbose_name_plural": "سئو ها",
            },
        ),
    ]
