# Generated by Django 5.1.5 on 2025-02-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0019_seo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seo",
            name="keywords",
            field=models.TextField(
                help_text="مثال: چاقو، موبایل، ...", verbose_name="Keywords"
            ),
        ),
    ]
