# Generated by Django 5.1.5 on 2025-02-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0021_product_keywords_delete_seo"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="visit_count",
            field=models.BigIntegerField(
                default=0, editable=False, verbose_name="تعداد بازدید"
            ),
        ),
    ]
