# Generated by Django 5.1.5 on 2025-03-12 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="setting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phones",
                to="site_settings_app.setting",
                verbose_name="تنظیم",
            ),
        ),
        migrations.AlterField(
            model_name="social",
            name="setting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="socials",
                to="site_settings_app.setting",
                verbose_name="تنظیم",
            ),
        ),
    ]
