# Generated by Django 5.1.5 on 2025-03-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings_app", "0002_alter_phone_setting_alter_social_setting"),
    ]

    operations = [
        migrations.RenameField(
            model_name="social",
            old_name="url",
            new_name="link",
        ),
    ]
