# Generated by Django 5.1.5 on 2025-03-15 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings_app", "0004_about_content_about_image_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="about",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="site_settings_app.about",
                verbose_name="درباره ما",
            ),
        ),
    ]
