# Generated by Django 5.1.5 on 2025-03-17 13:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings_app", "0005_alter_team_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="answer",
            field=models.TextField(blank=True, null=True, verbose_name="جواب"),
        ),
        migrations.AddField(
            model_name="contact",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 17, 13, 12, 0, 292485, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ ایجاد",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(default="", max_length=254, verbose_name="ایمیل"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="first_name",
            field=models.CharField(default="", max_length=25, verbose_name="نام"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="last_name",
            field=models.CharField(
                default="", max_length=25, verbose_name="نام خانوادگی"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="message",
            field=models.TextField(default="", verbose_name="پیام"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(
                default="",
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="باید عدد باشد.", regex="^[0-9]+$"
                    )
                ],
                verbose_name="شماره تلفن",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="status",
            field=models.CharField(
                choices=[("answered", "جواب داده شده"), ("pending", "در انتظار بررسی")],
                default="pending",
                max_length=100,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="subject",
            field=models.CharField(default="", max_length=100, verbose_name="عنوان"),
            preserve_default=False,
        ),
    ]
