# Generated by Django 5.1.5 on 2025-03-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "site_settings_app",
            "0006_contact_answer_contact_date_created_contact_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="date_created",
            field=models.DateTimeField(auto_created=True, verbose_name="تاریخ ایجاد"),
        ),
    ]
