# Generated by Django 5.1.5 on 2025-03-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings_app", "0007_alter_contact_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="date_created",
            field=models.DateTimeField(verbose_name="تاریخ ایجاد"),
        ),
    ]
