# Generated by Django 5.1.5 on 2025-03-18 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings_app", "0008_alter_contact_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AddField(
            model_name="notification",
            name="alert",
            field=models.TextField(default="", verbose_name="متن"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 18, 18, 20, 31, 111700, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ ایجاد",
            ),
            preserve_default=False,
        ),
    ]
