# Generated by Django 5.1.5 on 2025-02-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "سبد خرید", "verbose_name_plural": "سبد خریدها"},
        ),
    ]
